name: record_windows
description: Windows specific implementation for record package called by record_platform_interface.
version: 1.0.0-beta.2
homepage: https://github.com/llfbandit/record/tree/master/record_windows

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface: 
    git:
      url: git@github.com:radiosphere/record.git
      path: "./record_platform_interface"

  path: ^1.8.0

# dependency_overrides:
#   record_platform_interface:
#     path: ../record_platform_interface

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: record
    platforms:
      windows:
        pluginClass: RecordWindowsPluginCApi
