name: record_linux
description: Linux specific implementation for record package called by record_platform_interface.
version: 0.6.0
homepage: https://github.com/llfbandit/record/tree/master/record_linux

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface:
    git:
      url: git@github.com:radiosphere/record.git
      path: "record_platform_interface"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    implements: record
    platforms:
      linux:
        pluginClass: RecordLinuxPlugin
        dartPluginClass: RecordLinux
